// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package CCBuffers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CriticalServiceClient is the client API for CriticalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CriticalServiceClient interface {
	GetCriticalAccess(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*UserResponse, error)
}

type criticalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCriticalServiceClient(cc grpc.ClientConnInterface) CriticalServiceClient {
	return &criticalServiceClient{cc}
}

func (c *criticalServiceClient) GetCriticalAccess(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/main.CriticalService/GetCriticalAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CriticalServiceServer is the server API for CriticalService service.
// All implementations must embed UnimplementedCriticalServiceServer
// for forward compatibility
type CriticalServiceServer interface {
	GetCriticalAccess(context.Context, *ClientInfo) (*UserResponse, error)
	mustEmbedUnimplementedCriticalServiceServer()
}

// UnimplementedCriticalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCriticalServiceServer struct {
}

func (UnimplementedCriticalServiceServer) GetCriticalAccess(context.Context, *ClientInfo) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCriticalAccess not implemented")
}
func (UnimplementedCriticalServiceServer) mustEmbedUnimplementedCriticalServiceServer() {}

// UnsafeCriticalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CriticalServiceServer will
// result in compilation errors.
type UnsafeCriticalServiceServer interface {
	mustEmbedUnimplementedCriticalServiceServer()
}

func RegisterCriticalServiceServer(s grpc.ServiceRegistrar, srv CriticalServiceServer) {
	s.RegisterService(&CriticalService_ServiceDesc, srv)
}

func _CriticalService_GetCriticalAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CriticalServiceServer).GetCriticalAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.CriticalService/GetCriticalAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CriticalServiceServer).GetCriticalAccess(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// CriticalService_ServiceDesc is the grpc.ServiceDesc for CriticalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CriticalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.CriticalService",
	HandlerType: (*CriticalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCriticalAccess",
			Handler:    _CriticalService_GetCriticalAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
